### ISSUE TITLE
AttributeError: module 'custom_components.edge_tts.tts' has no attribute 'get_engine'

### ISSUE THREAD

**Issue by yfands** [hasscc/hass-edge-tts#70]
Version v0.7.2

Logger: homeassistant.components.tts.legacy
Bron: components/tts/legacy.py:137
integratie: Text-to-speech (TTS) (documentatie, problemen)
Eerst voorgekomen: 13:02:46 (1 gebeurtenis)
Laatst gelogd: 13:02:46

Error setting up platform: edge_tts
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tts/legacy.py", line 137, in async_setup_platform
    platform.get_engine, hass, p_config, discovery_info
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.edge_tts.tts' has no attribute 'get_engine'

**Comment by DoerakkerHA** [comment]
confirmed: 
2025-11-08 18:50:20.036 ERROR (MainThread) [homeassistant.components.tts.legacy] Error setting up platform: edge_tts
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tts/legacy.py", line 137, in async_setup_platform
    platform.get_engine, hass, p_config, discovery_info
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.edge_tts.tts' has no attribute 'get_engine'

Installation method
Home Assistant OS
Core
2025.11.1
Supervisor
2025.11.1
Operating System
16.3
Frontend
20251105.0

**Comment by sephrioth** [comment]
Same here

**Comment by CarlBird** [comment]
Also getting this error. I can provide details if needed.

**Comment by thomaspalmdk** [comment]
I am trying to figure out why this is not working with the latest version of Home Assistant (for me that is 2025.11), and the get_engine error is because you have the platform configured in configuration.yaml.
Remove it from configuration.yaml and use the UI to configure.

Then maybe you will be as lucky as I am...
Now I am just stuck at getting the integration working after configuring in the UI, it does not even start..

**Comment by lassikos** [comment]
Any updates on this? Does not work on 2025.11. I removed edge_tts removed from .yaml and restarted. Also tried to install previous version of this from HACS, no help.

**Comment by bcutter** [comment]
```
Logger: homeassistant.components.tts.legacy
Quelle: components/tts/legacy.py:137
Integration: Text-to-speech (TTS) (Dokumentation, Probleme)
Erstmals aufgetreten: 17:40:51 (1 Vorkommnis)
Zuletzt protokolliert: 17:40:51

Error setting up platform: edge_tts
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tts/legacy.py", line 137, in async_setup_platform
    platform.get_engine, hass, p_config, discovery_info
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.edge_tts.tts' has no attribute 'get_engine'
```

After following https://github.com/hasscc/hass-edge-tts/issues/70#issuecomment-3525582439 it seems fine. This should be handled more elegant. Leave a note in a release one has to switch from the YAML to the UI way of integrating it or something similar.
